### ISSUE TITLE
Fix the build pipeline

### ISSUE THREAD

**Issue by Talv** [SC2Mapster/blizzard-tutorials#16]
https://readthedocs.org/projects/s2editor-guides/builds/24175941/

> The required .readthedocs.yaml configuration file was not found at repository's root. Learn how to use this file in our [configuration file tutorial](https://docs.readthedocs.io/en/stable/config-file/index.html).

**Comment by Cristall** [comment]
https://readthedocs.org/projects/s2editor-guides/builds/24328819/
build is fixed, though the output looks different for tables:
![grafik](https://github.com/SC2Mapster/blizzard-tutorials/assets/761997/4720b240-f5b6-4105-b0a3-c624dc5649a0)
its harder to read, but at least no scrolling required

**Comment by Cristall** [comment]
seems like navigation area to the side doesnt work, only search

**Comment by Talv** [comment]
3d1f5ef74e26241c340dc306f32de69bd323a7c3
0c7188e54cce86c91d5b65cd54cd840888c3c9f8

Should be all good now.
